# 도커 설치에 필요한 기초 도구 설치
- name: Install dependencies for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

# 도커 공식 GPG 키 추가 및 APT 저장소 설정
- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# 도커 APT 저장소 추가
- name: Add Docker's APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

# 도커 저장소 추가 후 APT 캐시 업데이트
- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: yes 

# 도커 엔진과 도커 CLI 설치
- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

# 도커 서비스가 시스템 부팅 시 자동으로 시작되도록 설정
- name: Enable Docker service to start on boot
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  
  # 도커 그룹에 현재 사용자를 추가하여 도커 명령어를 sudo 없이 실행할 수 있도록 설정
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes 

# 도커 컴포즈 설치
- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'