#Nginx Docker 이미지 가져오기
- name: Pull Nginx Docker image
  community.docker.docker_image:
    name: nginx:latest
    source: pull

# Nginx 컨테이너 실행
- name: Run Nginx container
  community.docker.docker_container:
    name: web_server
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80" 